#ifndef _UK_TRACE_JBD2_H
#define _UK_TRACE_JBD2_H
#define trace_jbd2_checkpoint(...) do{}while(0)
#define trace_jbd2_checkpoint_stats(...) do{}while(0)
#define trace_jbd2_commit_flushing(...) do{}while(0)
#define trace_jbd2_commit_locking(...) do{}while(0)
#define trace_jbd2_commit_logging(...) do{}while(0)
#define trace_jbd2_drop_transaction(...) do{}while(0)
#define trace_jbd2_end_commit(...) do{}while(0)
#define trace_jbd2_handle_extend(...) do{}while(0)
#define trace_jbd2_handle_restart(...) do{}while(0)
#define trace_jbd2_handle_start(...) do{}while(0)
#define trace_jbd2_handle_stats(...) do{}while(0)
#define trace_jbd2_lock_buffer_stall(...) do{}while(0)
#define trace_jbd2_run_stats(...) do{}while(0)
#define trace_jbd2_shrink_checkpoint_list(...) do{}while(0)
#define trace_jbd2_shrink_count(...) do{}while(0)
#define trace_jbd2_shrink_scan_enter(...) do{}while(0)
#define trace_jbd2_shrink_scan_exit(...) do{}while(0)
#define trace_jbd2_start_commit(...) do{}while(0)
#define trace_jbd2_submit_inode_data(...) do{}while(0)
#define trace_jbd2_update_log_tail(...) do{}while(0)
#define trace_jbd2_write_superblock(...) do{}while(0)
#endif
