package io.neoterm.component.pm

import io.neoterm.App
import io.neoterm.R
import io.neoterm.component.ComponentManager
import io.neoterm.component.config.NeoPreference
import io.neoterm.component.config.NeoTermPath
import io.neoterm.framework.NeoTermDatabase
import io.neoterm.setup.proot.ProotManager
import io.neoterm.utils.NLog
import java.io.File
import java.net.URL
import java.nio.file.Files
import java.nio.file.Paths

object SourceHelper {
  /** Igaz, ha proot módban apt-alapú disztrón vagyunk (Ubuntu/Kali). */
  private fun isProotApt(): Boolean =
    NeoPreference.isProotEnabled() && ProotManager.selectedDistro().packageManager == "apt"

  /** Az apt list-könyvtár: proot módban a disztró rootfs-én belül. */
  private fun aptListsDir(): String =
    if (NeoPreference.isProotEnabled())
      "${ProotManager.selectedDistro().rootfsPath()}/var/lib/apt/lists"
    else NeoTermPath.PACKAGE_LIST_DIR

  /**
   * A sources.list írásának helye. Proot módban a disztró saját
   * sources.list-jét NEM írjuk felül, hanem egy külön drop-in fájlt használunk,
   * hogy a disztró eredeti forrásai épek maradjanak.
   */
  private fun aptSourcesFile(): String =
    if (NeoPreference.isProotEnabled())
      "${ProotManager.selectedDistro().rootfsPath()}/etc/apt/sources.list.d/neoterm.list"
    else NeoTermPath.SOURCE_FILE

  fun syncSource() {
    val sourceManager = ComponentManager.getComponent<PackageComponent>().sourceManager
    syncSource(sourceManager)
  }

  fun syncSource(sourceManager: SourceManager) {
    val content = buildString {
      this.append("# Generated by NeoTerm-Preference\n")
      sourceManager.getEnabledSources()
        .joinTo(this, "\n") { "deb [trusted=yes] ${it.url} ${it.repo}\n" }
    }
    kotlin.runCatching {
      val target = Paths.get(aptSourcesFile())
      target.parent?.let { Files.createDirectories(it) }
      Files.write(target, content.toByteArray())
    }
  }

  fun detectSourceFiles(): List<File> {
    val sourceFiles = ArrayList<File>()
    try {
      val listFiles = File(aptListsDir()).listFiles() ?: arrayOf()
      if (isProotApt()) {
        // A valódi disztró apt-indexei (a `<host>_..._Packages` fájlok), amiket
        // az `apt update` tölt le a rootfs-be — a teljes katalógus, nem csak a
        // (Termux-örökségű) konfigurált forrásokra szűrve.
        listFiles.filterTo(sourceFiles) { it.isFile && it.name.endsWith("Packages") }
      } else {
        val sourceManager = ComponentManager.getComponent<PackageComponent>().sourceManager
        val prefixes = sourceManager.getEnabledSources()
          .map { detectSourceFilePrefix(it) }
          .filter { it.isNotEmpty() }
        listFiles.filterTo(sourceFiles) { file ->
          prefixes.any { file.name.startsWith(it) }
        }
      }
    } catch (e: Exception) {
      sourceFiles.clear()
      NLog.e("PM", "Failed to detect source files: ${e.localizedMessage}")
    }

    return sourceFiles
  }

  fun detectSourceFilePrefix(source: Source): String {
    try {
      val url = URL(source.url)
      val builder = StringBuilder(url.host)
      if (url.port != -1) {
        builder.append(":${url.port}")
      }

      val path = url.path
      if (path != null && path.isNotEmpty()) {
        builder.append("_")
        val fixedPath = path.replace("/", "_").substring(1) // skip the last '/'
        builder.append(fixedPath)
      }
      builder.append("_dists_${source.repo.replace(" ".toRegex(), "_")}_binary-")
      return builder.toString()
    } catch (e: Exception) {
      NLog.e("PM", "Failed to detect source file prefix: ${e.localizedMessage}")
      return ""
    }
  }
}

class SourceManager internal constructor() {
  private val database = NeoTermDatabase.instance("sources")

  init {
    if (database.findAll<Source>(Source::class.java).isEmpty()) {
      App.get().resources.getStringArray(R.array.pref_package_source_values)
        .forEach {
          database.saveBean(Source(it, "stable main", true))
        }
    }
  }

  fun addSource(sourceUrl: String, repo: String, enabled: Boolean) {
    database.saveBean(Source(sourceUrl, repo, enabled))
  }

  fun removeSource(sourceUrl: String) {
    database.deleteBeanByWhere(Source::class.java, "url == '$sourceUrl'")
  }

  fun updateAll(sources: List<Source>) {
    database.dropAllTable()
    database.saveBeans(sources)
  }

  fun getAllSources(): List<Source> {
    return database.findAll(Source::class.java)
  }

  fun getEnabledSources(): List<Source> {
    return getAllSources().filter { it.enabled }
  }

  fun getMainPackageSource(): String {
    return getEnabledSources()
      .map { it.repo }
      .singleOrNull { it.trim() == "stable main" }
      ?: NeoTermPath.DEFAULT_MAIN_PACKAGE_SOURCE
  }

  fun applyChanges() {
    database.vacuum()
  }
}

